### ISSUE TITLE
Trouble in understanding database

### ISSUE THREAD

**Issue by Goel-Akash** [shubhamdhingra38/Spring-Boot-Auction-App#1]
Hey, I was having trouble understanding the tables used in the database. Can you help out with a schema or share MySQL queries?

**Comment by shubhamdhingra38** [comment]
@Goel-Akash I think local set up was broken. Ideally Hibernate sets up the entire database for you, so you don't need to touch the schema. I fixed the set up, and updated the instructions, could you try again?

**Comment by Goel-Akash** [comment]
I was able to access the application in localhost, but I am not able to register. It just says, "Could not register, please try again". Would you happen to have any idea how to resolve it?

**Comment by shubhamdhingra38** [comment]
Could you look at the logs in terminal where you ran `docker-compose up`? Also attach it here.

**Comment by Goel-Akash** [comment]
The Docker container log files for troubleshooting:
https://github.com/Goel-Akash/DockerLogs
